version: '3.8'

services:
  db:
    image: postgres:15.2-alpine
    container_name: Hapi-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - .db_data:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:
    external: true